POST http://localhost:8080/users/register
Content-Type: application/json

{

    "username": "Strddding",
    "password": "String",
    "email": "String@eff.com",
    "name": "String"
}

###
POST http://localhost:8080/tweets/postTweet
Content-Type: application/json

{
    "text": "This is a tweet",
    "user": "67d84182d56e277baacd0796"
    
}
